name: CI Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
      
      - name: Instalar dependências
        working-directory: ./tdw-aula-p3
        run: npm install

      - name: Verificar formatação com Prettier
        working-directory: ./tdw-aula-p3
        run: npm run prettier --check

  Lint:
    runs-on: ubuntu-latest
    needs: Prettier
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
      
      - name: Instalar dependências
        working-directory: ./tdw-aula-p3
        run: npm install

      - name: Executar Lint
        working-directory: ./tdw-aula-p3
        run: npm run lint

  Testes:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
      
      - name: Instalar dependências
        working-directory: ./tdw-aula-p3
        run: npm install

      - name: Executar testes com cobertura
        working-directory: ./tdw-aula-p3
        run: npm run test:coverage

  Build:
    runs-on: ubuntu-latest
    needs: [Prettier, Lint, Testes]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
      
      - name: Instalar dependências
        working-directory: ./tdw-aula-p3
        run: npm install

      - name: Compilar o projeto
        working-directory: ./tdw-aula-p3
        run: npm run build

      - name: Listar arquivos no diretório após o build
        working-directory: ./tdw-aula-p3
        run: ls
