name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier --check

  Lint:
    runs-on: ubuntu-latest
    needs: Prettier
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --site imartins-tdw-mctw-dev.netlify.app --auth nfp_PAHAZuM67DwkKNRX8yPya2qU5gK9YYYH1ad7 --prod
